name: "Validate Gradle Wrapper"
on:
  push:
    branches:
      - main
      - release/**
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
